### PR TITLE
Support fetch submodule by actions/checkout

### PR DESCRIPTION
**Pull request by bookshiyi**
## Changes

Support fetch submodule by actions/checkout in `build_test.yaml` and `formatting_test.yaml`

### CODE REVIEW

**Comment by temeddix** [comment]
I found out that Flutter 3.13's `dart format` has changed a little. If you're using Flutter SDK 3.10 or earlier, could you upgrade it with `flutter upgrade --force`?

**Comment by bookshiyi** [comment]
> 



> I found out that Flutter 3.13's `dart format` has changed a little. If you're using Flutter SDK 3.10 or earlier, could you upgrade it with `flutter upgrade --force`?

My Flutter version is 3.10.6, Dart version is 3.0.6.
I will attempt to upgrade SDKs.

**Comment by temeddix** [comment]
Okay :)

**Comment by bookshiyi** [comment]
@temeddix Ready to be merged.

**Comment by temeddix** [comment]
@bookshiyi Great, I also understand that this is needed for your new PR. Though the CI is not finished yet, because I'm confident that this won't break anything I'll merge it right away.

**Comment by bookshiyi** [comment]
> @bookshiyi Great, I also understand that this is needed for your new PR. Though the CI is not finished yet, because I'm confident that this won't break anything I'll merge it right away.

OK👌,thanks.

**Pull request merged**
