### PR TITLE
Add hetero ci

### PR DESCRIPTION
**Pull request by bookshiyi**
Support build test CI on ubuntu with aarch64, armv7, riscv

### CODE REVIEW

**Comment by bookshiyi** [comment]
I couldn't find a more elegant naming method (CI workflow, CI files) and how to elegant merge two ci files into one.
Give it to the greater coder.😀

**Comment by temeddix** [comment]
Hmm, I wonder if we can use matrix for archs too, will experiment :)

**Comment by temeddix** [comment]
Do you think it's possible to do these in only one `build_test.yaml` file? Looks like there are a lot of dupcliated code right now 👀

**Comment by bookshiyi** [comment]
> Do you think it's possible to do these in only one `build_test.yaml` file? Looks like there are a lot of dupcliated code right now 👀

Yeah, merge to one `build_test.yaml` file is a good idea, three-dimensional matrix composed of runner, target, arch is so elegant.

But here is a bigger issue: Multi-Arch based on qemu is supported by third party developer not GitHub official, so many workflow from actions marketplace couldn't be used, this is also the reason that why the PR been changed to draft.

**Comment by temeddix** [comment]
Late reply here 😅 though I've seen many GitHub projects with CI integrated, many of them were dealing with excessive CIs that were broken or not even working. That's because they added every CIs they thought they needed, but eventually it easily goes out of management and becomes unmaintained.

The reason to have one `build_test.yaml` is not only for readability, but also maintainability on project of this size(small yet). CI can support checking builds, but it would be be hard to guarantee everything, on every archs, IMO ;)

**Comment by temeddix** [comment]
@bookshiyi by the way, do you mind if I invite you to newly created GitHub team for this project? I sent a message via instagram and it seems you didn't saw it

**Comment by bookshiyi** [comment]
> Late reply here 😅 though I've seen many GitHub projects with CI integrated, many of them were dealing with excessive CIs that were broken or not even working. That's because they added every CIs they thought they needed, but eventually it easily goes out of management and becomes unmaintained.
> 
> The reason to have one `build_test.yaml` is not only for readability, but also maintainability on project of this size(small yet). CI can support checking builds, but it would be be hard to guarantee everything, on every archs, IMO ;)


Indeed, as you said, too much CI often makes maintenance difficult and eventually loses its meaning.

I attempted to add a variety of architectures to the compilation test only for improve stability of this project.
At present, it doesn't make much sense. It may even bring some maintenance trouble.
We might as well suspended it temporarily until it is needed.


-----


> @bookshiyi by the way, do you mind if I invite you to newly created GitHub team for this project? I sent a message via instagram and it seems you didn't saw it

Sorry to missed your message.
It's a pleasure to join the Github Team and work together, no problem.

**Comment by temeddix** [comment]
I'm still open to keeping this CI-per-architecture idea, so if we can use simple CI file then it will be good :)

**Pull request closed without merging**
