### PR TITLE
Update message code generation section documents

### PR DESCRIPTION
**Pull request by bookshiyi**
Update some message code generation documents and its structure.
How do you think about it?

### CODE REVIEW

**Comment by temeddix** [comment]
Great, I like the idea of adding that table here, but the list seems to be duplicated with this section over here:

image

Could you remove that list from 'Rust Resource API' page so that we can 'move' it to the 'Writing Code' page?

**Comment by temeddix** [comment]
Ultimately, it would be nice to make recursive `rinf message --watch` work on Linux as well, but that's another story :)

**Comment by bookshiyi** [comment]
> Great, I like the idea of adding that table here, but the list seems to be duplicated with this section over here:
> 
> image
> Could you remove that list from 'Rust Resource API' page so that we can 'move' it to the 'Writing Code' page?

yeah, the path list seems to be duplicated between two files. But it also related to pages Rust Resource API and Write Code.

How do you think about that separate `quick start`  from `documents`? for beginners and deeper users.

IMHO, maybe we cloud create a new page to explain `rinf command list` but not for tutorial.

Anyway, rinf's documents have been excellent under your maintenance.


> Ultimately, it would be nice to make recursive `rinf message --watch` work on Linux as well, but that's another story :)

The current file watcher is provided from official api: https://api.flutter.dev/flutter/dart-io/FileSystemEntity/watch.html

Here is a third party pub package : https://pub.dev/packages/watcher, maybe a worth choice to try.

**Comment by temeddix** [comment]
>Here is a third party pub package : https://pub.dev/packages/watcher, maybe a worth choice to try.

Yeah, this looks great. Looks like it's worth a shot :)

> create a new page to explain rinf command list but not for tutorial.

Yeah, it sounds good to let people know the available commands explicitly. Maybe we can give info about that `--help` argument like my commit, because any kind of duplication hinders clean maintenance. To be more specific, it might be very easy to leave the outdated info on one side, but only update things on the other.

**Comment by bookshiyi** [comment]
Yeah, It is very valuable to keep only one introduction.
`rinf --help` is a better entrance to explain how to use it than documents.

**Review by temeddix — APPROVED** [review]

**Pull request merged**
