### PR TITLE
Add CI support

### PR DESCRIPTION
**Pull request by bookshiyi**

### CODE REVIEW

**Comment by bookshiyi** [comment]
I am working hard on refactoring, achieving a similar effect

Screenshot 2023-08-14 at 13 29 05


 and, of course, the actions in the current pull request are functioning properly.

**Comment by temeddix** [comment]
I see, then should I wait for those changes to be pushed to this PR?

**Comment by bookshiyi** [comment]
@temeddix 
Merge the current pull request into the main branch anytime is surely OK.
I will create a new PR when I am ready.

**Comment by temeddix** [comment]
@bookshiyi I can see that workflows are working as expected on your branch! Thank you for this improvement, and I will be looking forword to new PRs :)

**Pull request merged**
