### PR TITLE
Update CI & fixed build wasm & update CI badge

### PR DESCRIPTION
**Pull request by bookshiyi**
1. Optimize CI log output
2. Parallel compilation
3. Build wasm work with GitHub actions #87

### CODE REVIEW

**Comment by temeddix** [comment]
It looks like `Future.wait` was causing the issue. Great job! I also like the parallelization of CI. I will merge this very soon :D

**Comment by bookshiyi** [comment]
Thanks for your reply.
It is a nice day for me that remote work with you.

**Comment by temeddix** [comment]
By default, workflow badge shows the status of the default branch, so I think the badges can be a bit more simple :)
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

From now on, the main branch of this repository will always have commits with only successful CI results. All contributors and maintainers including myself will always commit code via PR and CI.

**Comment by temeddix** [comment]
Also, I'll update matrix names to improve readability in GitHub actions page.

Current status:
image

**Comment by bookshiyi** [comment]
> Also, I'll update matrix names to improve readability in GitHub actions page.
> 
> Current status:

Feel free to edit the code without any concerns.


-----


> By default, workflow badge shows the status of the default branch, so I think the badges can be a bit more simple :) https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
> 
> From now on, the main branch of this repository will always have commits with only successful CI results. All contributors and maintainers including myself will always commit code via PR and CI.

You are right, it is clearly a more elegant and concise option.

**Comment by temeddix** [comment]
Hmm, it seems that if block doesn't work on powershell :\

**Comment by bookshiyi** [comment]
Cool~
The code and the logs have become very elegant!😃

**Comment by bookshiyi** [comment]
> Hmm, it seems that if block doesn't work on powershell :\

Yes, I couldn't figure out PowerShell before, so I opted for the built-in if condition of Actions.

**Comment by temeddix** [comment]
Now that the CI is passing, this PR can be merged! Thank you for valuable improvements.

**Pull request merged**
