### PR TITLE
Add `rinf message [-w|--watch]` command

### PR DESCRIPTION
**Pull request by bookshiyi**
## Changes

Add `rinf message [-w|--watch]` command for continuously compile `.proto` files when they changed.

Related to #169

### CODE REVIEW

**Comment by temeddix** [comment]
Wow, you really did this. Thanks for the improvement :D

I will take a look at this shortly

**Comment by temeddix** [comment]
Do you mind adding this new feature to the docs, perhaps by adding the 'Generating Message Code' section here?

- https://rinf-docs.cunarist.com/writing-code/

**Comment by bookshiyi** [comment]
Thank you for such a quick review and friendly reply.
It's a pity that I haven't been able to participate in the development of rinf for some time and salute you for making so many important contributions to rinf.

**Comment by temeddix** [comment]
Always enjoy working with you :) Couldn't have reached this far without you.

**Review by temeddix — APPROVED** [review]

**Pull request merged**
