### PR TITLE
Protobuf Instead of Msgpack

### LINKED ISSUE #118: Protobuf Implementation
I did saw a protobuf implementation issue a while ago. I don't know if its still the scope of the project or not. Not much of a rust or flutter developer but I do have it implemented already. If its still the scope of the project I would love to create a pr for protobuf implementation instead of a messagepack. (I am on a mac m1 so I cant test on mac or windows but I can verify it works well with android, ios and web)

### PR DESCRIPTION
**Pull request by wheregmis**
Fixes #118

Changes

- Replaced Msgpack serialization with Protocol Buffers for improved performance and compatibility.

- Updated build.rs to compile .proto files for Protocol Buffers.

- Modified serialization and deserialization functions to use Protobuf.

### CODE REVIEW

**Comment by temeddix** [comment]
Great! I will review this in a few hours, as I'm outdoors right now.

2 main things to improve here I see now here are:
- Automatic installation of protoc
- Using described folder path described in the goals(`./messages`)

**Comment by wheregmis** [comment]
Sure, waiting for your review and more feedback. This was just a basic implementation. I haven't used the add_seven method to increase the counter. Many more things can be polished.

**Comment by bookshiyi** [comment]
@wheregmis  It is worth celebrating that compile successfully on `arm64 macOS` and `x64 Windows`

**Comment by wheregmis** [comment]
@bookshiyi Well, that feels enough for me to motivate myself and not to be lazy to clean things up. 😂

**Review by bookshiyi — APPROVED** [review]

**Comment by bookshiyi** [comment]
Maybe need to install protobuf toolchain to CI environment.

Like this?

```
      - name: Setup Protobuf toolchain
          uses: arduino/setup-protoc@v2
```

**Comment by temeddix** [comment]
You can see the status here: https://github.com/orgs/cunarist/projects/2

**Comment by wheregmis** [comment]
Woke up to see all these above beautiful commits!!!! 😍 Incredible

**Comment by temeddix** [comment]
It's almost done, I think we'll approach 3.0 release in a few hours :)

**Comment by wheregmis** [comment]
Lol hats up to you guys to start working on my messy start hahaha 😂

**Comment by temeddix** [comment]
Though I did most of the template job, feel free to give other PRs afterwards if you have ideas for improvements :D

**Comment by wheregmis** [comment]
Sure, so far, everything looks super clean. I will keep checking and updating you if something can be improved. Amazing job guys.

**Review by temeddix — APPROVED** [review]

**Comment by temeddix** [comment]
@wheregmis Thank you for your contribution!

**Pull request merged**
