### PR TITLE
Allow some optimization

### PR DESCRIPTION
**Pull request by vlad9486**
Add a method that allows better performance. The future can be reused for each message and efficiently polled without unsafe code and unnecessary allocations.

### CODE REVIEW

**Comment by temeddix** [comment]
What do you think about changing the `recv` implementation instead of adding a new method? The code would look like this:

```rust
impl<T> SignalReceiver<T> {
    /// Asynchronously receives the next message from the queue. Only the active
    /// receiver is allowed to receive messages. If there are no messages in the
    /// queue, the receiver will wait until a new message is sent.
    /// If this receiver is not active, the future will return `None`.
    pub fn recv(&self) -> impl Future<Output = Option<T>> {
        RecvFuture {
            inner: self.inner.clone(),
            receiver_id: self.id, // Pass the receiver's ID to the future
        }
    }
}
```

From the users' perspective, the receiver API will stay the same because `async fn` in Rust implicitly returns `impl Future` type.

**Comment by vlad9486** [comment]
I agree, I was not sure that the API would be 100% compatible. 

I would also like to make `RecvFuture` public and return the concrete type, so I can store it in a structure.

**Comment by temeddix** [comment]
I am not sure if exposing internal structs to the user would be ideal, because its names and features were intended to be used internally. Would it be possible to make your code use `impl Future` type annotations to store futures?

**Comment by vlad9486** [comment]
Ok then, I will use `Box<dyn ...>`. I have adapted the commit, please review.

**Comment by temeddix** [comment]
Thank you for your understanding. Perhaps you can use a generic type `<T: Future>` as well. I'll publish the new version as soon as possible.

**Pull request merged**
